apiVersion: apps/v1
kind: Deployment
metadata:
  name: triggerRallye
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: triggerRallye
  template:
    metadata:
      labels:
        app: triggerRallye
    spec:
      containers:
      - image: milou666/triggerrally
        name: triggerRallye
        ports:
        - containerPort: 80