apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-server
  namespace: default
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  triggerservice
                port:
                  number: 80